### ISSUE TITLE
Adding AdvancedRocketry to my pack w/TomsMod crashes

### ISSUE THREAD

**Issue by iTraumatik** [tom5454/Toms-Mod#13]
@tom5454 

https://gist.github.com/iTraumatik/bd81d9d3262a353c37720dc5a5f504ca
https://gist.github.com/iTraumatik/232f3558ce9c3abf3857a13958e7c2a3
https://gist.github.com/iTraumatik/e00997b5322de8c1ab442891983ac4cb
crashlog-
https://gist.github.com/iTraumatik/d7561100c5f2aba4d6c94648f02b55fb

**Comment by tom5454** [comment]
I don't think this is on my end. Try testing with only AdvancedRocketry installed, and try reporting it at the AdvancedRocketry issue tracker.

**Comment by iTraumatik** [comment]
@tom5454 

I tried AdvRocket in a clean new instance and it works fine with same settings as my pack instance.  Then i tried AdvRocket and my mods minus Tom'sMod and it works fine.  Then when i add Tom'sMod to it i get the crashes as listed above.  I reported this error over at AW github issues also at the same time as here.
https://github.com/zmaster587/AdvancedRocketry/issues/281#issuecomment-259559739

**Comment by tom5454** [comment]
Do you use the vanilla mc launcher? If not try loading the pack with it.

**Comment by iTraumatik** [comment]
I mainly use MultiMC, tried stable and Dev version.  Just tried curse (close launcher after launch option) and got the same thing.

at zmaster587.libVulpes.items.ItemProjector.registerMachine(ItemProjector.java:97)
    at zmaster587.advancedRocketry.AdvancedRocketry.postInit(AdvancedRocketry.java:1153)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:600)
    at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:239)
    at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:217)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:142)
    at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:800)
    at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:324)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:520)

**Comment by tom5454** [comment]
I have 0 idea what causing that.

**Comment by iTraumatik** [comment]
K thanks for the help.   Just installed the pack to vanilla and same as above.  No optifine, Java 8v111(recommended by them for security and performance, lowest on site for 8).   I was using lower versions of forge until most mods started using higher versions.  On 2122 in MultiMC, Curse , and vanilla.  Thanks again

**Comment by tom5454** [comment]
No problem, If you find any bugs in Tom's Mod please report them here.

**Comment by iTraumatik** [comment]
@tom5454  zmaster587 tracked down what was going on.  "I think i figured it out. It's looking like tom's mod is registering a block as coilCopper, but then the block is either not added, or removed from the minecraft block registry. So when the holo projector goes to figure out how many of each block is required to make a machine, an NPE is thrown. I have yet to 100% exaclty how this is happening, but it's definatly something along those lines."
He is adding a workaround to his mod and will be in his next update.  But i thought i would let you know just incase this is something wrong in your mod. Thanks again.

**Comment by tom5454** [comment]
I have an item with oredict name of coilCopper, and the code thinks its a block.

**Comment by iTraumatik** [comment]
Ah , ok , thats what he thinks the conflict was then.  He reproduced the error then has a fix for his coming , thanks
